//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class NewWayModelContainer : DbContext
{
    public NewWayModelContainer()
        : base("name=NewWayModelContainer")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }
    public virtual DbSet<Territory> Territories { get; set; }
    public virtual DbSet<NewWayDealer> NewWayDealers { get; set; }
    public virtual DbSet<NewWayEShowroom> NewWayEShowrooms { get; set; }
    public virtual DbSet<NewWayEShowType> NewWayEShowTypes { get; set; }
    public virtual DbSet<NewWayModel> NewWayModels { get; set; }
    public virtual DbSet<NewWayStyle> NewWayStyles { get; set; }
    public virtual DbSet<NewWayCapacity> NewWayCapacities { get; set; }
    public virtual DbSet<NewWayChassisMake> NewWayChassisMakes { get; set; }
    public virtual DbSet<NewWaySaleStatus> NewWaySaleStatus { get; set; }
    public virtual DbSet<NewWayEShowPhotos> NewWayEShowPhotos { get; set; }
    public virtual DbSet<ServiceSupportType> ServiceSupportTypes { get; set; }
    public virtual DbSet<ServiceSupportManual> ServiceSupportManuals { get; set; }
    public virtual DbSet<ServiceSupportTruck> ServiceSupportTrucks { get; set; }
    public virtual DbSet<signupSubscribers> signupSubscribers { get; set; }
    public virtual DbSet<WebsiteInquiry> WebsiteInquiries { get; set; }
    public virtual DbSet<InquiryType> InquiryTypes { get; set; }
    public virtual DbSet<TruckWarranty> TruckWarranties { get; set; }
    public virtual DbSet<RSVPInquiry> RSVPInquiries { get; set; }
}
