//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class InquiryType
{
    public InquiryType()
    {
        this.WebsiteInquiries = new HashSet<WebsiteInquiry>();
    }

    public int Id { get; set; }
    public string Type { get; set; }

    public virtual ICollection<WebsiteInquiry> WebsiteInquiries { get; set; }
}

public partial class NewWayCapacity
{
    public int Id { get; set; }
    public string Capacity { get; set; }
    public int NewWayModelId { get; set; }

    public virtual NewWayModel NewWayModel { get; set; }
}

public partial class NewWayChassisMake
{
    public NewWayChassisMake()
    {
        this.NewWayEShowrooms = new HashSet<NewWayEShowroom>();
    }

    public int Id { get; set; }
    public string ChassisMake { get; set; }

    public virtual ICollection<NewWayEShowroom> NewWayEShowrooms { get; set; }
}

public partial class NewWayDealer
{
    public NewWayDealer()
    {
        this.NewWayEShowrooms = new HashSet<NewWayEShowroom>();
    }

    public int Id { get; set; }
    public string BusinessName { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public int TerritoryId { get; set; }
    public string Zipcode { get; set; }
    public string Phone { get; set; }
    public string Fax { get; set; }
    public string WebAddress { get; set; }
    public int UserProfileId { get; set; }

    public virtual Territory Territory { get; set; }
    public virtual ICollection<NewWayEShowroom> NewWayEShowrooms { get; set; }
}

public partial class NewWayEShowPhotos
{
    public int Id { get; set; }
    public int EShowroomId { get; set; }
    public string PhotoPath { get; set; }
    public string ThumbPath { get; set; }
    public string Caption { get; set; }
    public Nullable<bool> isPrimaryPhoto { get; set; }
    public string PDFPath { get; set; }

    public virtual NewWayEShowroom NewWayEShowroom { get; set; }
}

public partial class NewWayEShowroom
{
    public NewWayEShowroom()
    {
        this.NewWayEShowPhotos = new HashSet<NewWayEShowPhotos>();
    }

    public int Id { get; set; }
    public int NewWayDealerId { get; set; }
    public int ShowTypeId { get; set; }
    public string WorkOrder { get; set; }
    public int ModelId { get; set; }
    public string Hours { get; set; }
    public int Year { get; set; }
    public int ChassisMakeId { get; set; }
    public string Transmission { get; set; }
    public string GVM { get; set; }
    public string GVWR { get; set; }
    public Nullable<int> Mileage { get; set; }
    public string Comments { get; set; }
    public int SaleStatusId { get; set; }
    public Nullable<System.DateTime> DateSubmitted { get; set; }
    public Nullable<System.DateTime> DateSold { get; set; }
    public string DeclineNotes { get; set; }
    public int CapacityId { get; set; }
    public Nullable<byte> NewListing { get; set; }
    public Nullable<System.DateTime> DateEmailNotificationSent { get; set; }
    public Nullable<byte> EmailNotificationSent { get; set; }
    public string Engine { get; set; }

    public virtual NewWayDealer NewWayDealer { get; set; }
    public virtual NewWayEShowType NewWayEShowType { get; set; }
    public virtual NewWayModel NewWayModel { get; set; }
    public virtual NewWayChassisMake NewWayChassisMake { get; set; }
    public virtual NewWaySaleStatus NewWaySaleStatus { get; set; }
    public virtual ICollection<NewWayEShowPhotos> NewWayEShowPhotos { get; set; }
    public virtual NewWayCapacity NewWayCapacity { get; set; }
}

public partial class NewWayEShowType
{
    public NewWayEShowType()
    {
        this.NewWayEShowrooms = new HashSet<NewWayEShowroom>();
    }

    public int Id { get; set; }
    public string ShowType { get; set; }

    public virtual ICollection<NewWayEShowroom> NewWayEShowrooms { get; set; }
}

public partial class NewWayModel
{
    public NewWayModel()
    {
        this.NewWayEShowrooms = new HashSet<NewWayEShowroom>();
        this.NewWayCapacities = new HashSet<NewWayCapacity>();
        this.ServiceSupportTrucks = new HashSet<ServiceSupportTruck>();
    }

    public int Id { get; set; }
    public string Model { get; set; }
    public int StyleId { get; set; }
    public string TruckImage { get; set; }
    public string SpecSheetPath { get; set; }
    public string YouTubeLink { get; set; }

    public virtual NewWayStyle NewWayStyle { get; set; }
    public virtual ICollection<NewWayEShowroom> NewWayEShowrooms { get; set; }
    public virtual ICollection<NewWayCapacity> NewWayCapacities { get; set; }
    public virtual ICollection<ServiceSupportTruck> ServiceSupportTrucks { get; set; }
}

public partial class NewWaySaleStatus
{
    public NewWaySaleStatus()
    {
        this.NewWayEShowrooms = new HashSet<NewWayEShowroom>();
    }

    public int Id { get; set; }
    public string Status { get; set; }

    public virtual ICollection<NewWayEShowroom> NewWayEShowrooms { get; set; }
}

public partial class NewWayStyle
{
    public NewWayStyle()
    {
        this.NewWayModels = new HashSet<NewWayModel>();
    }

    public int Id { get; set; }
    public string Style { get; set; }

    public virtual ICollection<NewWayModel> NewWayModels { get; set; }
}

public partial class RSVPInquiry
{
    public int Id { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string company { get; set; }
    public string email { get; set; }
    public string attending { get; set; }
    public string hotelAccommodations { get; set; }
    public string phone { get; set; }
    public string country { get; set; }
    public string state { get; set; }
    public string comments { get; set; }
    public System.DateTime dateSubmitted { get; set; }
}

public partial class ServiceSupportManual
{
    public ServiceSupportManual()
    {
        this.ServiceSupportTrucks = new HashSet<ServiceSupportTruck>();
    }

    public int Id { get; set; }
    public string Filename { get; set; }
    public string FileDescription { get; set; }
    public int ServiceSupportTypeId { get; set; }
    public string VideoLink { get; set; }
    public Nullable<bool> publicAccess { get; set; }

    public virtual ServiceSupportType ServiceSupportType { get; set; }
    public virtual ICollection<ServiceSupportTruck> ServiceSupportTrucks { get; set; }
}

public partial class ServiceSupportTruck
{
    public ServiceSupportTruck()
    {
        this.ServiceSupportManuals = new HashSet<ServiceSupportManual>();
    }

    public int Id { get; set; }
    public Nullable<System.DateTime> BuildDate { get; set; }
    public string SerialNumberText { get; set; }
    public string VIN { get; set; }
    public Nullable<bool> DealerTruck { get; set; }
    public int NewWayModelId { get; set; }

    public virtual NewWayModel NewWayModel { get; set; }
    public virtual ICollection<ServiceSupportManual> ServiceSupportManuals { get; set; }
}

public partial class ServiceSupportType
{
    public ServiceSupportType()
    {
        this.ServiceSupportManuals = new HashSet<ServiceSupportManual>();
    }

    public int Id { get; set; }
    public string SupportType { get; set; }

    public virtual ICollection<ServiceSupportManual> ServiceSupportManuals { get; set; }
}

public partial class signupSubscribers
{
    public int Id { get; set; }
    public string email { get; set; }
    public Nullable<byte> subscribe { get; set; }
    public string firstname { get; set; }
    public string lastname { get; set; }
    public string state { get; set; }
    public string company { get; set; }
    public string phone { get; set; }
    public string country { get; set; }
    public string nwtInterest { get; set; }
    public string comments { get; set; }
    public Nullable<System.DateTime> signupDate { get; set; }
}

public partial class Territory
{
    public Territory()
    {
        this.NewWayDealers = new HashSet<NewWayDealer>();
    }

    public int Id { get; set; }
    public string state { get; set; }
    public string abbreviation { get; set; }

    public virtual ICollection<NewWayDealer> NewWayDealers { get; set; }
}

public partial class TruckWarranty
{
    public int Id { get; set; }
    public System.DateTime DateSubmitted { get; set; }
    public int NewWayDealerId { get; set; }
    public string WarrantyJson { get; set; }
    public byte[] WarrantyPdf { get; set; }
    public string CustomerName { get; set; }
    public string ChassisVIN { get; set; }
    public string SellingDealer { get; set; }
}

public partial class UserProfile
{
    public int Id { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string company { get; set; }
    public string address { get; set; }
    public string city { get; set; }
    public string state { get; set; }
    public string zipCode { get; set; }
    public string country { get; set; }
    public string phone { get; set; }
    public string website { get; set; }
    public string userId { get; set; }
    public Nullable<int> NewWayDealerId { get; set; }
    public string titleRole { get; set; }
}

public partial class WebsiteInquiry
{
    public int Id { get; set; }
    public System.DateTime dateSubmitted { get; set; }
    public Nullable<System.DateTime> followUpCompleted { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string company { get; set; }
    public string jobTitle { get; set; }
    public string address { get; set; }
    public string city { get; set; }
    public string state { get; set; }
    public string country { get; set; }
    public string zip { get; set; }
    public string testimonial { get; set; }
    public Nullable<byte> testimonialPhoto { get; set; }
    public string comments { get; set; }
    public string newWayInterest { get; set; }
    public string kPacInterest { get; set; }
    public Nullable<byte> infoCustomApparel { get; set; }
    public Nullable<byte> cobraFlyer { get; set; }
    public Nullable<byte> cobraMagnumFlyer { get; set; }
    public Nullable<byte> kingCobraFlyer { get; set; }
    public Nullable<byte> diamonbackFlyer { get; set; }
    public Nullable<byte> viperFlyer { get; set; }
    public Nullable<byte> mambaFlyer { get; set; }
    public Nullable<byte> mammothFlyer { get; set; }
    public Nullable<byte> westernSeriesMammothFlyer { get; set; }
    public Nullable<byte> sidewinderFlyer { get; set; }
    public Nullable<byte> rotoPacFlyer { get; set; }
    public int InquiryTypeId { get; set; }
    public string eShowroomTruckInterest { get; set; }
    public string archived { get; set; }
    public string interestArea { get; set; }
    public string qtyDesired { get; set; }

    public virtual InquiryType InquiryType { get; set; }
}
